### ISSUE TITLE
Setting up multiple hapi-sass routes

### ISSUE THREAD

**Issue by EyePulp** [mdarnall/hapi-sass#12]
Howdy;
I have a lot of my hapi code broken into separate plugins.  Within the `exports.register` method of two distinct plugins, I have two distinct hapi-sass setups.  I notice only one works at a time however.  Ech plugin maintains its own static directory, and the routePath value is distinct between them, but for some reason only one route seems to register - I can turn off one and the other works and vice-versa, so the overall syntax seems correct.
```javascript
    server.register({register:require('hapi-sass'), options: {
        src            : `${__dirname}/static/css/src`,
        dest           : `${__dirname}/static/css/dist`,
        force          : true,
        debug          : !isprod,
        routePath      : '/quote/static/css/{file}.css',
        includePaths   : [`${__dirname}/static/css/src/incs`],
        outputStyle    : isprod?'compressed':'nested',
        sourceComments : !isprod,
        srcExtension   : 'scss',
    }});
```

Any suggestions?  Should there be a conflict, or is there a reason I can't call `server.register` from within the `exports.register` method of a plugin?

Thanks for the work on this feature, btw -- makes life a lot easier.

**Comment by EyePulp** [comment]
So I figured out the issue, and it's pretty basic -- just the need for `mutliple:true` in the `register.attributes` object.  It works in local testing, and looking through the code didn't reveal any obvious problems.  PR attached.  Thanks!

**Comment by mdarnall** [comment]
Cool, glad you figured out what the issue was. Going to close this and get your change in.
