### ISSUE TITLE
Update node-sass version so Node 8 linux compatible

### ISSUE THREAD

**Issue by steevhise** [mdarnall/hapi-sass#17]
Running hapi-sass latest under Debian 9, Node 8, gave me ` Error: Node Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime (57)`  I figured out that this is because hapi-sass was specifying node-sass v3.13.1.  changing package.json to specify latest node-sass fixes this.

**Comment by steevhise** [comment]
I just submitted a PR for this.

**Comment by mdarnall** [comment]
Resolved with hapi-sass 3.0.0
