### ISSUE TITLE
hapi 17

### ISSUE THREAD

**Issue by steevhise** [mdarnall/hapi-sass#19]
Any plan to port to hapi 17?

**Comment by mdarnall** [comment]
Not at the moment as I'm not really doing Hapi Development, but PRs are welcome. If it's an easy change I might be able to do it.

**Comment by emanuelet** [comment]
I created that PR https://github.com/mdarnall/hapi-sass/pull/20

**Comment by baronworks** [comment]
Any word on this?

**Comment by mdarnall** [comment]
fixed in #21
