### ISSUE TITLE
Allow .sass extension!

### ISSUE THREAD

**Issue by digitaldesigndj** [mdarnall/hapi-sass#4]
https://github.com/mdarnall/hapi-sass/blob/master/index.js#L59

I saw this in the source code, but it took a long while of wondering why the plugin just would not work.

**Comment by digitaldesigndj** [comment]
This pull request should take care of the issue: https://github.com/mdarnall/hapi-sass/pull/5

**Comment by mdarnall** [comment]
Awesome! Ya, I never had it there because I always used `.scss`.
