### ISSUE TITLE
documentation and example should include REQUIRED inert plugin

### ISSUE THREAD

**Issue by abritinthebay** [mdarnall/hapi-sass#9]
hapi-sass requires the `reply.file` interface from Hapi - which doesn't exist unless you have the `inert` plugin (from Walmart Labs, creators of Hapi) registered with the server.

I can fork the readme and add this but didn't want to presume... ;)

**Comment by mdarnall** [comment]
Interesting. This didn't used to be the case. What version of Hapi split that out?

**Comment by abritinthebay** [comment]
I think Hapi post... v9 (or maybe v8) split out the `reply.file` api into Inert.

I'm using Hapi `11.1.4` in this case.

**Comment by abritinthebay** [comment]
I don't know if it needs to be an explicit dep in the npm sense. Perhaps a PeerDep would work though.

**Comment by mdarnall** [comment]
Looks like it was [v9.0](https://github.com/hapijs/hapi/issues/2682)

I'm thinking this _should_ be an explicit dependency, just like how `hoek` or `boom` is because it's used directly. Also, the release notes for `v9.0` mention:

>If you are already loading plugins, simply add the ones from the list that you want to your plugin list. If you are not, use the server.register() method to load these. Remember to add the plugins you need to your package.json file.

>If you have plugins that depend on these features, make sure to specify it using the server.dependency() method.

**Comment by abritinthebay** [comment]
Oh as a `server.dependency`? that makes perfect sense yeah.

**Comment by mdarnall** [comment]
closing in favor of #10
